root: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
env:
  browser: true
parserOptions:
  sourceType: module
rules:
  no-param-reassign: off
  no-plusplus: off
  no-restricted-globals: off
  no-restricted-syntax: off
  no-underscore-dangle: off

  default-case: off
  prefer-const:
    - error
    - destructuring: all
  strict:
    - error
    - safe

  import/prefer-default-export: off
  import/no-extraneous-dependencies: off
overrides:
  - files:
      - dist/plugin.js
      - nightwatch.conf.js
      - test/func-*.js
      - test/func/**/*.js
    parserOptions:
      sourceType: script
